Para lanzar una excepcion se utiliza -*-> throw

Se maneja con Try, catch, finally